spring.application.name=appdemo

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:C:/Users/Tejodeep Bose/Desktop/appdemo/data/testdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
